apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: rabbitmq
spec:
  hosts:
  - {{ .Values.host }}
  gateways:
  - {{ .Values.gateway }}
  http:
  - match:
    - port: 80
    - port: 443
    route:
    - destination:
        host: rabbitmq
        port:
          number: 15672
  tcp:
  - match:
    - port: 31672
    route:
    - destination:
        host: rabbitmq
        port:
          number: 5672