server:
  port: 80
  servlet:
    session:
      cookie:
        name: MYSELF
  tomcat:
    max-http-form-post-size: 25MB
    remoteip:
      remote-ip-header: X-Forwarded-For
      protocol-header: X-Forwarded-Proto

my:
  config:
    ctx: https://myself.renlm.cn
    wsHost: ws://myself.renlm.cn
    wssHost: wss://myself.renlm.cn:443
    wsAllowedOrigins: http://myself.renlm.cn,https://myself.renlm.cn
    proxyLogConcurrency: 30-50

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:123654}

encrypt:
  keyStore:
    location: classpath:keyStore.jks
    password: ${KEY_STORE_PASSWORD:storepass}
    alias: ${KEY_STORE_ALIAS:alias}
    secret: ${KEY_STORE_SECRET:keypass}

aj:
  captcha:
    cacheType: redis
    jigsaw: classpath:images/jigsaw
    picClick: classpath:images/pic-click
    type: default
    waterMark: myself.renlm.cn
    slipOffset: 5
    aesStatus: true
    interferenceOptions: 0

mica:
  xss:
    enabled: true
    trimText: true
    mode: clear
    prettyPrint: false
    enableEscape: false
    pathPatterns: /**
    pathExcludePatterns:
    - /static
    - /webjars
    - /markdown/**

logging:
  level:
    root: info
    cn.renlm.graph: info
  file:
    name: /opt/log/myself.log
  logback:
    rollingpolicy:
      maxFileSize: 512MB
      maxHistory: 30

mybatis-plus:
  configuration:
    localCacheScope: STATEMENT
  global-config:
    db-config:
      update-strategy: IGNORED

management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: ${spring.application.name}

spring:
  application:
    name: myself
  profiles:
    active: prod
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  thymeleaf:
    cache: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  data:
    redis:
      database: 4
      host: redis
      port: 6379
      password: ENC(kvMVW92bXK7Ym2drMqz81542HlHnpGWV+1FMPnjXcctU/Q0bAtQuN2rLe16BAZE3ZCOn+CWhThK/Qsep+/q8/xG4YV03mdP+grGgQXUXeTg=)
      timeout: 10s
      lettuce:
        pool:
          maxActive: 256
          maxWait: 2000ms
          maxIdle: 10
          minIdle: 5
  rabbitmq:
    virtual-host: ENC(7Ie8vh6wtP2aOHXlRAJk8SH8DKexZA/35ZK4VawvHhreNwezpLzav5/f5V8QUvag)
    host: rabbitmq
    port: 5672
    username: ENC(6bCmM/8Y+zaFcFns3lq1Zkca9Zva6box+mE8cijqUeZsji/HuriTMu19X4gi3JaL)
    password: ENC(YUg37CIjBBx8+cd2RGn/rfPwiz3SHt+8Fp901VTZGvihenrTPJWjv0wmqnmnrDbXHKeXttyu7+4XLfloCqTD2N0SQXrIGp+n7uphB1EMosc=)
    listener:
      direct:
        missing-queues-fatal: false
  datasource:
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          url: jdbc:mysql://mysql:3306/myself?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true
          username: ENC(/55z3xkUTQDh4UfepMXH6fdk4rcQvRimwN2IRIxJS7FxB0WEaeOMVlsptt82Ys9B)
          password: ENC(DP2Al147pJyiFArv67h0Pm08fFWjX9Ktjyri2jXjBm4ZWYsnSwXBwOsdk7ndmNmKJu8QjXCg7oDhIqQy9HnAcw==)
          driver-class-name: com.mysql.cj.jdbc.Driver
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            misfireThreshold: 60000
            clusterCheckinInterval: 5000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true