# -DDB_INIT_MODE={ALWAYS|NEVER}
# -DCONFIGSERVER={https://default:123654@config.renlm.cn}
spring:
  application:
    name: mygraph
  main:
    allowCircularReferences: true
  profiles:
    active: ${PROFILES_ACTIVE:dev}
  config:
    import: configserver:${CONFIGSERVER:https://default:123654@config.renlm.cn}
  cloud:
    config:
      name: mygraph,logging,actuator
      profile: ${spring.profiles.active}
      label: master
      failFast: true