fullnameOverride: redis
requirepass: PWD
nodeSelector: {}
image:
  repository: redis
  pullPolicy: IfNotPresent
  tag: 7.2.4
serviceAccount:
  create: false
ingress:
  enabled: false
service:
  type: NodePort
  port: 6379
  nodePort: 30379