fullnameOverride: redis
appVersion: latest
gateway: istio-ingress/gateway
host: redis.renlm.cn
nodeSelector: {}
image:
  repository: redis
  pullPolicy: IfNotPresent
  tag: latest
serviceAccount:
  create: false
ingress:
  enabled: false
service:
  type: NodePort
  port: 6379
  nodePort: 30379