fullnameOverride: mygraph
replicaCount: 1
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
tolerations: []
affinity: {}
configmap:
  enabled: true
serviceAccount:
  create: true
  annotations: {}
  name: mygraph-sa
service:
  type: ClusterIP
  port: 8080
actuator:
  port: 9000
  portName: tcp-actuator
  health:
    liveness:
      initialDelaySeconds: 3
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 20
      timeoutSeconds: 1
    readiness:
      initialDelaySeconds: 3
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 20
      timeoutSeconds: 1
resources:
  limits:
    memory: 4Gi
    cpu: 2
  requests:
    memory: 500Mi
    cpu: 200m
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 95
mysql:
  nodeSelector: {}
  service:
    type: NodePort
    port: 3306
    nodePort: 30306
rabbitmq:
  nodeSelector: {}
  service:
    type: NodePort
    port: 15672
    amqpPort: 5672
    amqpNodePort: 30672
redis:
  nodeSelector: {}
  service:
    type: NodePort
    port: 6379
    nodePort: 30379
jenkins:
  nodeSelector: {}
  service:
    type: ClusterIP
    port: 8080