apiVersion: v2
name: mygraph
version: 1.0.1
icon: https://renlm.github.io/favicon.ico
description: MyGraph 管理后台，集成经典RABC权限管理、Oauth2.0认证服务、在线画图、ER模型设计与在线文档管理，是一个高度集成的后台模板。
keywords:
- RABC权限管理
- Oauth2.0认证
- 在线画图
- ER模型设计
- 文档管理
dependencies:
- condition: redis.enabled
  name: redis
  repository: file://./charts/redis
- condition: mysql.enabled
  name: mysql
  repository: file://./charts/mysql
- condition: rabbitmq.enabled
  name: rabbitmq
  repository: file://./charts/rabbitmq
- condition: jenkins.enabled
  name: jenkins
  repository: file://./charts/jenkins