apiVersion: v1
kind: ConfigMap
metadata:
  name: mygraph-configmap
data:
  dev.yaml: |-
    server:
      port: 80
      servlet:
        session:
          cookie:
            name: MYGRAPH
      tomcat:
        remoteip:
          remote-ip-header: X-Forwarded-For
          protocol-header: X-Forwarded-Proto
    my:
      config:
        ctx: https://mygraph.renlm.cn
        wsHost: ws://mygraph.renlm.cn
        wssHost: wss://mygraph.renlm.cn:443
        wsAllowedOrigins: http://mygraph.renlm.cn,https://mygraph.renlm.cn
        chrome:
          driverPath: /usr/bin/chromedriver
          sleepTime: 2500
    encrypt:
      keyStore:
        location: classpath:keyStore.jks
        password: ${KEY_STORE_PASSWORD:storepass}
        alias: ${KEY_STORE_ALIAS:alias}
        secret: ${KEY_STORE_SECRET:keypass}
    aj:
      captcha:
        cacheType: redis
        jigsaw: classpath:images/jigsaw
        picClick: classpath:images/pic-click
        type: default
        waterMark: mygraph.renlm.cn
        slipOffset: 5
        aesStatus: true
        interferenceOptions: 0
    mica:
      xss:
        enabled: true
        trimText: true
        mode: clear
        prettyPrint: false
        enableEscape: false
        pathPatterns: /**
        pathExcludePatterns:
        - /static
        - /webjars
        - /markdown/**
    logging:
      level:
        root: info
        cn.renlm.mygraph: info
      file:
        name: /opt/log/mygraph.log
      logback:
        rollingpolicy:
          maxFileSize: 512MB
          maxHistory: 30
    mybatis-plus:
      configuration:
        localCacheScope: STATEMENT
      global-config:
        db-config:
          update-strategy: IGNORED
    management:
      server:
        port: 9000
      endpoints:
        web:
          exposure:
            include: prometheus
      metrics:
        tags:
          application: mygraph
    spring:
      application:
        name: mygraph
      profiles:
        active: dev
      main:
        allow-circular-references: true
      servlet:
        multipart:
          max-file-size: 30MB
          max-request-size: 30MB
      thymeleaf:
        cache: true
      jackson:
        serialization:
          WRITE_DATES_AS_TIMESTAMPS: true
      data:
        redis:
          database: 1
          host: mygraph-devops-fleet-redis
          port: 6379
          password: PWD@20xx$
          timeout: 10s
          lettuce:
            pool:
              maxActive: 256
              maxWait: 2000ms
              maxIdle: 10
              minIdle: 5
      rabbitmq:
        virtual-host: /mygraph
        host: mygraph-devops-fleet-rabbitmq
        port: 5672
        username: mygraph
        password: PWD@20xx$
      datasource:
        dynamic:
          primary: master
          strict: true
          datasource:
            master:
              url: jdbc:mysql://mygraph-devops-fleet-mysql:3306/mygraph?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true
              username: mygraph
              password: PWD@20xx$
              driver-class-name: com.mysql.cj.jdbc.Driver
      quartz:
        job-store-type: jdbc
        jdbc:
          initialize-schema: never
        properties:
          org:
            quartz:
              scheduler:
                instanceId: AUTO
              jobStore:
                class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
                driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
                tablePrefix: QRTZ_
                isClustered: true
                misfireThreshold: 60000
                clusterCheckinInterval: 5000
                useProperties: false
              threadPool:
                class: org.quartz.simpl.SimpleThreadPool
                threadCount: 10
                threadPriority: 5
                threadsInheritContextClassLoaderOfInitializingThread: true
