# 需要先安装 rancher-monitoring 应用
# https://grafana.com/grafana/dashboards/12900
# https://ranchermanager.docs.rancher.com/zh/v2.6/how-to-guides/advanced-user-guides/monitoring-alerting-guides/customize-grafana-dashboard
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus.fullname" . }}-service-monitor
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  endpoints:
  - interval: 30s
    port: {{ .Values.portName }}
    path: /actuator/prometheus
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- range .Values.selector }}
        {{ .name | nindent 6 }}: {{ .value }}
      {{- end }}
