server:
  port: 80
  servlet:
    context-path: /dev
    
mybatis-plus:
  configuration:
    localCacheScope: STATEMENT
    cacheEnabled: true
  global-config:
    db-config:
      update-strategy: IGNORED

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  thymeleaf:
    cache: false
  jackson: 
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  security:
    user:
      name: graph
      password: Aa123456^
      roles: admin
  datasource:
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          url: jdbc:mysql://renlm.cn:3306/graph?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true
          username: graph
          password: Kusbnjlsdi^df4K_fywm86erp7IMYt^tn504
          driver-class-name: com.mysql.cj.jdbc.Driver
          init:
            schema: classpath:schema/MySQL/schema.sql
            data: classpath:schema/MySQL/data.sql
            continue-on-error: false
            separator: ";"