server:
  port: 80
  servlet:
    context-path: /mygraph
    
my:
  config:
    ctx: http://localhost/mygraph
    wsHost: ws://localhost
    wsAllowedOrigins: http://localhost
    proxyLogConcurrency: 10-15
    
mica:
  xss:
    enabled: true
    trim-text: true
    mode: clear
    pretty-print: false
    enable-escape: true
    path-patterns: /**
    path-exclude-patterns: 
      - /static
      - /webjars
      - /markdown/**
    
logging:
  level:
    root: info
    cn.renlm.graph: debug
  file:
    name: /opt/log/mygraph.log
    max-size: 10MB
    max-history: 7
    
mybatis-plus:
  configuration:
    localCacheScope: STATEMENT
  global-config:
    db-config:
      update-strategy: IGNORED

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  thymeleaf:
    cache: false
  jackson: 
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  redis:
    host: renlm.cn
    port: 6479
    timeout: 6000
    password: K86erp7ssdi^_fyIMYmf4Kwt^tn50jl4bn
    database: 1
    client-name: dev
  rabbitmq:
    virtual-host: dev
    host: renlm.cn
    port: 5672
    username: dev
    password: K86erp7ssdi^_fyIMYmf4Kwt^tn50jl4bn
    listener:
      direct:
        missing-queues-fatal: false
  datasource:
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          url: jdbc:mysql://renlm.cn:3306/dev?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true
          username: dev
          password: K86erp7ssdi^_fyIMYmf4Kwt^tn50jl4bn
          driver-class-name: com.mysql.cj.jdbc.Driver
          init:
            schema: classpath:schema/schema.sql
            data: classpath:schema/data.sql
            continue-on-error: false
            separator: ";"
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            misfireThreshold: 60000
            clusterCheckinInterval: 5000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true