server:
  port: 80
  servlet:
    context-path: /mygraph
    
my:
  config:
    wsHost: ws://localhost
    wsAllowedOrigins: http://localhost
    
logging:
  level:
    root: info
    cn.renlm.graph: debug
  file:
    name: /opt/log/my-graph.log
    max-size: 10MB
    max-history: 7
    
mybatis-plus:
  configuration:
    localCacheScope: STATEMENT
  global-config:
    db-config:
      update-strategy: IGNORED

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  thymeleaf:
    cache: false
  jackson: 
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  redis:
    host: renlm.cn
    port: 6379
    timeout: 6000
    password: Rscl@GR12t2Kcs.d^_^Yhm8K7^_^0rr8df170l@G
    database: 3
    client-name: my-graph
  rabbitmq:
    virtual-host: /renlm
    host: renlm.cn
    port: 5672
    username: renlm
    password: MR1tMQdf1Q@7^_^02Kit8Rabb2K8bbiG70l@cs^_^YhmRa
    listener:
      direct:
        missing-queues-fatal: false
  datasource:
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          url: jdbc:mysql://renlm.cn:3306/graph?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true
          username: graph
          password: Kusbnjlsdi^df4K_fywm86erp7IMYt^tn504
          driver-class-name: com.mysql.cj.jdbc.Driver
          init:
            schema: classpath:schema/schema.sql
            data: classpath:schema/data.sql
            continue-on-error: false
            separator: ";"
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            misfireThreshold: 60000
            clusterCheckinInterval: 5000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true