server:
  port: 80
  servlet:
    context-path: /mygraph

my:
  config:
    ctx: http://localhost/mygraph
    wsHost: ws://localhost
    wsAllowedOrigins: http://localhost
    proxyLogConcurrency: 10-15

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:123654}

encrypt:
  keyStore:
    location: classpath:keyStore.jks
    password: ${KEY_STORE_PASSWORD:storepass}
    alias: ${KEY_STORE_ALIAS:alias}
    secret: ${KEY_STORE_SECRET:keypass}

aj:
  captcha:
    cacheType: redis
    jigsaw: classpath:images/jigsaw
    picClick: classpath:images/pic-click
    type: default
    waterMark: mygraph.renlm.cn
    slipOffset: 5
    aesStatus: true
    interferenceOptions: 0

mica:
  xss:
    enabled: true
    trim-text: true
    mode: clear
    pretty-print: false
    enable-escape: true
    path-patterns: /**
    path-exclude-patterns:
    - /static
    - /webjars
    - /markdown/**

logging:
  level:
    root: info
    cn.renlm.graph: debug
  file:
    name: /opt/log/mygraph.log
  logback:
    rollingpolicy:
      maxFileSize: 512MB
      maxHistory: 30

mybatis-plus:
  configuration:
    localCacheScope: STATEMENT
  global-config:
    db-config:
      update-strategy: IGNORED

management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: ${spring.application.name}

spring:
  application:
    name: mygraph
  profiles:
    active: dev
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  thymeleaf:
    cache: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  data:
    redis:
      database: 3
      host: ENC(7t07SoGx3YNZQ18Jo1gu/j9yHoxJ0pxG8Y1tXE7OEQDWh+oc6kZHD49Tp+we682t)
      port: ENC(6Hk9Fr716xYOKeWkspYz08UnTkOS6npDvn+2eUZJPTSL5rSn6ZkfN1E+5EYCJUTP)
      password: ENC(kvMVW92bXK7Ym2drMqz81542HlHnpGWV+1FMPnjXcctU/Q0bAtQuN2rLe16BAZE3ZCOn+CWhThK/Qsep+/q8/xG4YV03mdP+grGgQXUXeTg=)
      timeout: 10s
      lettuce:
        pool:
          maxActive: 256
          maxWait: 2000ms
          maxIdle: 10
          minIdle: 5
  rabbitmq:
    virtual-host: ENC(zePGodUsbK9mPRDZI5dYuZL20lMh+J5/9qCh6jYUk0+iYaUD2LhVyVG/XUGXC2I7)
    host: ENC(7t07SoGx3YNZQ18Jo1gu/j9yHoxJ0pxG8Y1tXE7OEQDWh+oc6kZHD49Tp+we682t)
    port: ENC(PyTYL2Yu5KovwOE41EP81FMjHp/6U1x7hPTWJPdAJ6wPfGP9ZtSz/1W1piRbc/20)
    username: ENC(dAwEPtF2sMl/lGe0DESwgVjgezRafykLVBsVmnBVD0ZoQWzxzrxP75eVtzijsqUr)
    password: ENC(+DZNeJTRNilmAua20ZJQj8jbsAkXhOH4jHpYUi+Vygeg0UiEkDWsmFt0OYA782UX8gyQ5JOeB6hLpXom+wcg6GjiCFSHOj/4X/VeNmz0r8Y=)
    listener:
      direct:
        missing-queues-fatal: false
  datasource:
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          url: ENC(/0ecf3cS2HEnTd5c7pv64Pt0LSGTddWMgoYRikEC5rmIDyZbsmwp9ENHi/gZSMagMq5misO1CcrrARDPfHL5bMUj6O95rVPcqjtUPqjEHuTM3i99UybSemLyNrJ0H9xaKXBqSFSQhSCuZpwphOdr1vTZZvb9deCvhkV32zRPtF1hg4A8vQ0vjQP2ZN0KzEsGaRWoeQ5c4fAag4QiaWhVTA==)
          username: ENC(TH8gokJSLbQ6b+3miT2omUUP2ymJzM14ItGSYD9dZ2W4/pzFusZeCvwkuY1nFL4l)
          password: ENC(DP2Al147pJyiFArv67h0Pm08fFWjX9Ktjyri2jXjBm4ZWYsnSwXBwOsdk7ndmNmKJu8QjXCg7oDhIqQy9HnAcw==)
          driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schemaLocations:
      - classpath:db/schema/schema.sql
      - classpath:db/schema/oauth2.sql
      - classpath:org/springframework/security/oauth2/server/authorization/oauth2-authorization-schema.sql
      - classpath:org/springframework/security/oauth2/server/authorization/oauth2-authorization-consent-schema.sql
      - classpath:org/springframework/security/oauth2/server/authorization/client/oauth2-registered-client-schema.sql
      dataLocations:
      - classpath:db/data/data.sql
      - classpath:db/data/oauth2.sql
      continueOnError: false
      separator: ;
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            misfireThreshold: 60000
            clusterCheckinInterval: 5000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true