apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-configmap
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
  redis.conf: |-
    requirepass $(echo -n $(REQUIREPASS) | base64 -d)
    protected-mode no
    port {{ .Values.service.port }}
    databases 16
    dir /var/lib/redis
