apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: redis
spec:
  hosts:
  - {{ .Values.host }}
  gateways:
  - {{ .Values.gateway }}
  tcp:
  - match:
    - port: 31379
    route:
    - destination:
        host: redis
        port:
          number: 6379