apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: tcp
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
