{{- if .Values.nfs.enabled -}}
{{- $fullName := include "jenkins.fullname" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-pvc
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  storageClassName: {{ $fullName }}-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nfs.storage }}
{{- end -}}