{{- $fullName := include "jenkins.fullname" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  serviceName: {{ $fullName }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "jenkins.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "jenkins.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: jnlp
              containerPort: 50000
              protocol: TCP
          volumeMounts:
            - name: root-m2
              mountPath: /root/.m2
            - name: docker-bin
              mountPath: /usr/bin/docker
            - name: docker-daemon
              mountPath: /etc/docker/daemon.json
              subPath: daemon.json
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: root-m2
          hostPath:
            path: /root/.m2
        - name: docker-bin
          hostPath:
            path: /usr/bin/docker
        - name: docker-daemon
          hostPath:
            path: /etc/docker
        - name: docker-sock
          hostPath: 
            path: /var/run/docker.sock
        {{- if .Values.nfs.enabled }}
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: {{ $fullName }}-pvc
        {{- else }}
        - name: jenkins-home
          hostPath: 
            path: /var/jenkins_home
        {{- end }}
