apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: mygraph-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      protocol: HTTP
      name: http
    hosts:
    - mygraph.renlm.cn
  - port:
      number: 443
      protocol: HTTPS
      name: https
    hosts:
    - mygraph.renlm.cn
    tls:
      mode: SIMPLE
      credentialName: istio-system.renlm.cn
      minProtocolVersion: TLSV1_2