# https://opentelemetry.io/zh/docs/collector/configuration/#receivers
# https://github.com/open-telemetry/opentelemetry-operator/tree/main/cmd/otel-allocator#prometheuscr-specifics
# https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md
# https://github.com/jaegertracing/jaeger/tree/main/docker-compose/monitor
apiVersion: v1
kind: List
items:
- apiVersion: opentelemetry.io/v1alpha1
  kind: OpenTelemetryCollector
  metadata:
    name: otel
    namespace: istio-system
  spec:
    mode: statefulset
    image: otel/opentelemetry-collector-contrib:0.99.0
    config: |-
      receivers:
        otlp:
          protocols:
            grpc: {}
            http: {}
      processors:
        batch: {}
      exporters:
        logging:
          verbosity: detailed
        prometheus:
          endpoint: 0.0.0.0:8889
          namespace: span_metrics
        zipkin:
          endpoint: http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans
      connectors:
        spanmetrics:
          histogram:
            explicit:
              buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
          dimensions:
          - name: http.method
            default: GET
          - name: http.status_code
          exemplars:
            enabled: true
          exclude_dimensions: [status.code]
          dimensions_cache_size: 1000
          aggregation_temporality: AGGREGATION_TEMPORALITY_CUMULATIVE
          metrics_flush_interval: 15s
          metrics_expiration: 5m
          events:
            enabled: true
            dimensions:
            - name: exception.type
            - name: exception.message
          resource_metrics_key_attributes:
          - service.name
          - telemetry.sdk.language
          - telemetry.sdk.name
      service:
        pipelines:
          metrics/spanmetrics:
            receivers: [spanmetrics]
            exporters: [prometheus]
          traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [spanmetrics, zipkin]
          logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [logging]
- apiVersion: telemetry.istio.io/v1alpha1
  kind: Telemetry
  metadata:
    name: otel-istio
    namespace: istio-system
  spec:
    tracing:
    - providers:
      - name: otel-tracing
      randomSamplingPercentage: 1.00
      customTags:
        provider:
          literal:
            value: otel-tracing
- apiVersion: opentelemetry.io/v1alpha1
  kind: Instrumentation
  metadata:
    name: java-instrumentation
  spec:
    propagators:
    - tracecontext
    - baggage
    - b3
    sampler:
      type: parentbased_always_on
    java:
      image: otel/autoinstrumentation-java:latest
      env:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf
      - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
        value: http://otel-collector.istio-system:4318/v1/metrics
      - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        value: http://otel-collector.istio-system:4318/v1/traces
      - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
        value: http://otel-collector.istio-system:4318/v1/logs