# https://github.com/open-telemetry/opentelemetry-operator/tree/main/cmd/otel-allocator#prometheuscr-specifics
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: opentelemetry-targetallocator-sa
    namespace: observability
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: opentelemetry-targetallocator-cr
  rules:
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    - podmonitors
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: opentelemetry-targetallocator-crb
    namespace: observability
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: opentelemetry-targetallocator-cr
  subjects:
  - kind: ServiceAccount
    name: opentelemetry-targetallocator-sa
    namespace: observability
- apiVersion: telemetry.istio.io/v1alpha1
  kind: Telemetry
  metadata:
    name: otel-istio
    namespace: istio-system
  spec:
    tracing:
    - providers:
      - name: otel-tracing
      randomSamplingPercentage: 1
      customTags:
        tracing:
          literal:
            value: opentelemetry
- apiVersion: opentelemetry.io/v1alpha1
  kind: OpenTelemetryCollector
  metadata:
    name: otel
    namespace: observability
  spec:
    mode: statefulset
    targetAllocator:
      enabled: true
      serviceAccount: opentelemetry-targetallocator-sa
      prometheusCR:
        enabled: true
    config: |-
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
        prometheus:
          target_allocator:
            endpoint: http://otel-targetallocator-service
            interval: 30s
            collector_id: ${POD_NAME}
      processors:
        memory_limiter:
          check_interval: 1s
          limit_percentage: 75
          spike_limit_percentage: 15
        batch:
          send_batch_size: 100
          timeout: 10s
      exporters:
        zipkin:
          endpoint: http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans
      extensions:
        health_check:
          port: 13133
      service:
        extensions:
        - health_check
        pipelines:
          metrics:
            receivers:
            - prometheus
            processors:
            - memory_limiter
            - batch
            exporters:
            - zipkin
          traces:
            receivers:
            - otlp
            processors:
            - memory_limiter
            - batch
            exporters:
            - zipkin
- apiVersion: opentelemetry.io/v1alpha1
  kind: Instrumentation
  metadata:
    name: java-instrumentation
  spec:
    propagators:
      - tracecontext
      - baggage
      - b3
    sampler:
      type: always_on
    java:
      image: otel/autoinstrumentation-java:latest