# https://github.com/open-telemetry/opentelemetry-operator/tree/main/cmd/otel-allocator#prometheuscr-specifics
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: observability
- apiVersion: telemetry.istio.io/v1alpha1
  kind: Telemetry
  metadata:
    name: otel-istio
    namespace: istio-system
  spec:
    tracing:
    - providers:
      - name: otel-tracing
      randomSamplingPercentage: 1
      customTags:
        tracing:
          literal:
            value: opentelemetry
- apiVersion: opentelemetry.io/v1alpha1
  kind: OpenTelemetryCollector
  metadata:
    name: otel-sidecar
    namespace: observability
  spec:
    mode: sidecar
    config: |-
      receivers:
        jaeger:
          protocols:
            thrift_compact: {}
      processors:
        memory_limiter:
          check_interval: 1s
          limit_percentage: 75
          spike_limit_percentage: 15
        batch:
          send_batch_size: 100
          timeout: 10s
      exporters:
        debug: {}
        zipkin:
          endpoint: http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans
      extensions:
        health_check:
          port: 13133
      service:
        extensions:
        - health_check
        pipelines:
          traces:
            receivers: [jaeger]
            processors:
            - memory_limiter
            - batch
            exporters: 
            - debug
            - zipkin