apiVersion: v1
kind: List
items:
- apiVersion: telemetry.istio.io/v1alpha1
  kind: Telemetry
  metadata:
    name: otel-istio
    namespace: istio-system
  spec:
    tracing:
    - providers:
      - name: otel-tracing
      randomSamplingPercentage: 100.0
      customTags:
        provider:
          literal:
            value: otel-tracing
- apiVersion: opentelemetry.io/v1alpha1
  kind: Instrumentation
  metadata:
    name: java-instrumentation
  spec:
    propagators:
    - tracecontext
    - baggage
    - b3
    sampler:
      type: parentbased_always_on
    java:
      image: otel/autoinstrumentation-java:latest
      env:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector.istio-system:4318