# https://github.com/open-telemetry/opentelemetry-operator/tree/main/cmd/otel-allocator#prometheuscr-specifics
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: opentelemetry-targetallocator-sa
    namespace: observability
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: opentelemetry-targetallocator-cr
  rules:
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    - podmonitors
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: opentelemetry-targetallocator-crb
    namespace: observability
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: opentelemetry-targetallocator-cr
  subjects:
  - kind: ServiceAccount
    name: opentelemetry-targetallocator-sa
    namespace: observability
- apiVersion: telemetry.istio.io/v1alpha1
  kind: Telemetry
  metadata:
    name: otel-istio
    namespace: istio-system
  spec:
    tracing:
    - providers:
      - name: otel-tracing
      randomSamplingPercentage: 1
      customTags:
        tracing:
          literal:
            value: opentelemetry
- apiVersion: opentelemetry.io/v1alpha1
  kind: OpenTelemetryCollector
  metadata:
    name: otel
    namespace: observability
  spec:
    mode: statefulset
    targetAllocator:
      enabled: true
      serviceAccount: opentelemetry-targetallocator-sa
      prometheusCR:
        enabled: true
    config: |-
      receivers:
        otlp:
          protocols:
            grpc: {}
            http: {}
        prometheus:
          target_allocator:
            endpoint: http://otel-targetallocator-service
            interval: 30s
            collector_id: ${POD_NAME}
      exporters:
        zipkin:
          endpoint: zipkin.istio-system.svc.cluster.local:9411
          tls:
            insecure: true
          sending_queue:
            enabled: true
          retry_on_failure:
            enabled: true
      service:
        pipelines:
          metrics:
            receivers:
            - prometheus
            exporters:
            - zipkin
          traces:
            receivers:
            - otlp
            exporters:
            - zipkin