# https://opentelemetry.io/zh/docs/collector/configuration/#receivers
# https://github.com/open-telemetry/opentelemetry-operator/tree/main/cmd/otel-allocator#prometheuscr-specifics
# https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md
# https://github.com/jaegertracing/jaeger/tree/main/docker-compose/monitor
apiVersion: v1
kind: List
items:
- apiVersion: opentelemetry.io/v1alpha1
  kind: OpenTelemetryCollector
  metadata:
    name: otel
    namespace: istio-system
  spec:
    mode: statefulset
    image: otel/opentelemetry-collector-contrib:0.99.0
    config: |-
      receivers:
        otlp:
          protocols:
            grpc: {}
            http: {}
        prometheus:
          config:
            scrape_configs:
            - job_name: jaeger-collector
              scrape_interval: 15s
              static_configs:
              - targets: [tracing.istio-system:14269]
      processors:
        batch: {}
      exporters:
        logging:
          verbosity: detailed
        prometheus:
          endpoint: 0.0.0.0:8889
          namespace: span_metrics
        otlp:
          endpoint: jaeger-collector.istio-system:14268
          tls:
            insecure: true
      connectors:
        spanmetrics: {}
      service:
        pipelines:
          metrics/spanmetrics:
            receivers: [otlp, prometheus, spanmetrics]
            exporters: [prometheus]
          traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [spanmetrics, otlp]
          logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [logging]
- apiVersion: telemetry.istio.io/v1alpha1
  kind: Telemetry
  metadata:
    name: otel-istio
    namespace: istio-system
  spec:
    tracing:
    - providers:
      - name: otel-tracing
      randomSamplingPercentage: 100.00
      customTags:
        provider:
          literal:
            value: otel-tracing
- apiVersion: opentelemetry.io/v1alpha1
  kind: Instrumentation
  metadata:
    name: java-instrumentation
  spec:
    propagators:
    - tracecontext
    - baggage
    - b3
    sampler:
      type: parentbased_always_on
    java:
      image: otel/autoinstrumentation-java:latest
      env:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector.istio-system:4318