# https://opentelemetry.io/zh/docs/collector/configuration/#receivers
# https://github.com/open-telemetry/opentelemetry-operator/tree/main/cmd/otel-allocator#prometheuscr-specifics
apiVersion: v1
kind: List
items:
- apiVersion: opentelemetry.io/v1alpha1
  kind: OpenTelemetryCollector
  metadata:
    name: otel-sidecar
  spec:
    mode: sidecar
    config: |-
      receivers:
        jaeger:
          protocols:
            thrift_compact: {}
      processors:
        memory_limiter:
          check_interval: 1s
          limit_percentage: 75
          spike_limit_percentage: 15
        batch:
          send_batch_size: 100
          timeout: 10s
      exporters:
        debug: {}
        zipkin:
          endpoint: http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans
      extensions:
        health_check:
          port: 13133
      service:
        extensions:
        - health_check
        pipelines:
          traces:
            receivers:
            - jaeger
            processors:
            - memory_limiter
            - batch
            exporters:
            - debug
            - zipkin
- apiVersion: opentelemetry.io/v1alpha1
  kind: Instrumentation
  metadata:
    name: java-instrumentation
  spec:
    propagators:
    - tracecontext
    - baggage
    - b3
    sampler:
      type: parentbased_always_on
    java:
      image: otel/autoinstrumentation-java:latest