# https://opentelemetry.io/zh/docs/collector/configuration/#receivers
# https://github.com/open-telemetry/opentelemetry-operator/tree/main/cmd/otel-allocator#prometheuscr-specifics
# https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md
# https://github.com/jaegertracing/jaeger/tree/main/docker-compose/monitor
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: istio-system
spec:
  mode: statefulset
  image: otel/opentelemetry-collector:latest
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    processors:
      batch: {}
    exporters:
      logging:
        verbosity: detailed
      prometheus:
        endpoint: 0.0.0.0:8889
        namespace: span_metrics
      zipkin:
        endpoint: http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans
    connectors:
      spanmetrics: {}
    service:
      pipelines:
        metrics/spanmetrics:
          receivers:
          - spanmetrics
          processors: []
          exporters:
          - prometheus
        traces:
          receivers:
          - otlp
          processors:
          - batch
          exporters:
          - spanmetrics
          - zipkin
        logs:
          receivers:
          - otlp
          processors:
          - batch
          exporters:
          - logging