apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: jaeger-pod-monitor
  namespace: istio-system
  labels:
    app: jaeger
spec:
  podMetricsEndpoints:
  - interval: 5s
    path: /metrics
    port: admin-http
  namespaceSelector:
    matchNames:
    - istio-system
  selector:
    matchLabels:
      app: jaeger