apiVersion: v1
kind: List
items:
- apiVersion: monitoring.coreos.com/v1
  kind: PodMonitor
  metadata:
    name: jaeger-component-monitor
    namespace: istio-system
    labels:
      monitoring: jaeger-components
  spec:
    podMetricsEndpoints:
    - interval: 15s
      path: /metrics
      port: admin-http
    namespaceSelector:
      matchNames:
      - istio-system
    selector:
      matchExpressions:
      - key: app.kubernetes.io/managed-by
        operator: In
        values:
        - jaeger-operator