apiVersion: v1
kind: List
items:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: otel-collector-monitor
    namespace: observability
    labels:
      monitoring: otel-collectors
  spec:
    endpoints:
    - interval: 15s
      port: prometheus
      path: /metrics
    namespaceSelector:
      matchNames:
      - observability
    selector:
      matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values:
        - opentelemetry-collector
      - key: operator.opentelemetry.io/collector-headless-service
        operator: DoesNotExist
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: mygraph-component-monitor
    labels:
      monitoring: mygraph-components
  spec:
    endpoints:
    - interval: 15s
      port: tcp-actuator
      path: /actuator/prometheus
    selector:
      matchExpressions:
      - key: instrumentation.opentelemetry.io/inject-java
        operator: In
        values:
        - true