apiVersion: v1
kind: List
items:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: otel-metrics-monitor
    namespace: observability
    labels:
      monitoring: otel-metrics
  spec:
    endpoints:
    - interval: 15s
      port: prometheus
      path: /metrics
    selector:
      matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values:
        - opentelemetry-collector
      - key: operator.opentelemetry.io/collector-headless-service
        operator: DoesNotExist
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: mygraph-prometheus-monitor
    labels:
      monitoring: metrics
  spec:
    endpoints:
    - interval: 15s
      port: tcp-actuator
      path: /actuator/prometheus
    selector:
      matchExpressions:
      - key: app
        operator: In
        values:
        - mygraph