apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jaeger-service-monitor
  labels:
    release: prometheus
spec:
  endpoints:
  - interval: 30s
    port: tcp-prometheus
    path: /metrics
  namespaceSelector:
    matchNames:
    - renlm
  selector:
    matchLabels:
      app: mygraph