apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: otel-istio
  namespace: istio-system
spec:
  tracing:
  - providers:
    - name: otel-tracing
    randomSamplingPercentage: 100
    customTags:
      tracing:
        literal:
          value: opentelemetry