apiVersion: v1
kind: Namespace
metadata:
  name: letsencrypt
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: istio-letsencrypt-issuer
  namespace: letsencrypt
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: renlm@21cn.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: istio-letsencrypt-issuer
    # Enable the HTTP-01 challenge provider
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - selector: {}
      http01:
        ingress:
          # istio | nginx | traefik
          class: istio
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-system.renlm.cn
  namespace: istio-system
spec:
  secretName: istio-system.renlm.cn
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
      - istio-system.renlm.cn
  dnsNames:
    - redis.renlm.cn
    - mysql.renlm.cn
    - amqp.renlm.cn
    - rabbitmq.renlm.cn
    - jenkins.renlm.cn
    - mygraph.renlm.cn
    - kubernetes.renlm.cn
  issuerRef:
    name: istio-letsencrypt-issuer
    kind: ClusterIssuer