apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: istiok8s
    namespace: kube-system
    labels:
      component: kube-apiserver
      tier: control-plane
  spec:
    ClusterIP: None
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    selector:
      component: kube-apiserver
      tier: control-plane
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: kubernetes
  spec:
    hosts:
    - kubernetes.renlm.cn
    gateways:
    - istio-system/mygraph-gateway
    tls:
    - match:
      - port: 443
        sniHosts:
        - kubernetes.renlm.cn
      route:
      - weight: 100
        destination:
          host: istiok8s.kube-system.svc.cluster.local
          port:
            number: 443
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: mygraph
  spec:
    hosts:
    - mygraph.renlm.cn
    gateways:
    - istio-system/mygraph-gateway
    http:
    - match:
      - port: 80
      - port: 443
      route:
      - weight: 100
        destination:
          host: mygraph
          port:
            number: 8080
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: jenkins
  spec:
    hosts:
    - jenkins.renlm.cn
    gateways:
    - istio-system/mygraph-gateway
    http:
    - match:
      - port: 80
      - port: 443
      route:
      - weight: 100
        destination:
          host: jenkins
          port:
            number: 8080
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: rabbitmq
  spec:
    hosts:
    - rabbitmq.renlm.cn
    gateways:
    - istio-system/mygraph-gateway
    http:
    - match:
      - port: 80
      - port: 443
      route:
      - weight: 100
        destination:
          host: rabbitmq
          port:
            number: 15672
    tcp:
    - match:
      - port: 5672
      route:
      - weight: 100
        destination:
          host: rabbitmq
          port:
            number: 5672
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: mysql
  spec:
    hosts:
    - mysql.renlm.cn
    gateways:
    - istio-system/mygraph-gateway
    tcp:
    - match:
      - port: 3306
      route:
      - weight: 100
        destination:
          host: mysql
          port:
            number: 3306
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: redis
  spec:
    hosts:
    - redis.renlm.cn
    gateways:
    - istio-system/mygraph-gateway
    tcp:
    - match:
      - port: 6379
      route:
      - weight: 100
        destination:
          host: redis
          port:
            number: 6379