apiVersion: v1
kind: List
items:
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: mygraph
  spec:
    hosts:
    - mygraph.renlm.cn
    gateways:
    - istio-system/mygraph-gateway
    http:
    - match:
      - port: 80
      - port: 443
      route:
      - weight: 100
        destination:
          host: mygraph
          port:
            number: 8080
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: mygraph-jenkins
  spec:
    hosts:
    - jenkins.renlm.cn
    gateways:
    - istio-system/mygraph-gateway
    http:
    - match:
      - port: 80
      - port: 443
      route:
      - weight: 100
        destination:
          host: mygraph-jenkins
          port:
            number: 8080
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: mygraph-rabbitmq
  spec:
    hosts:
    - rabbitmq.renlm.cn
    gateways:
    - istio-system/mygraph-gateway
    http:
    - match:
      - port: 80
      - port: 443
      route:
      - weight: 100
        destination:
          host: mygraph-rabbitmq
          port:
            number: 15672
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: tcp-redis
  spec:
    hosts:
    - redis.renlm.cn
    gateways:
    - istio-system/mygraph-gateway
    tcp:
    - match:
      - port: 31400
      route:
      - weight: 100
        destination:
          host: mygraph-redis
          port:
            number: 6379
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: tcp-mysql
  spec:
    hosts:
    - mysql.renlm.cn
    gateways:
    - istio-system/mygraph-gateway
    tcp:
    - match:
      - port: 31400
      route:
      - weight: 100
        destination:
          host: mygraph-mysql
          port:
            number: 3306
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: tcp-amqp
  spec:
    hosts:
    - amqp.renlm.cn
    gateways:
    - istio-system/mygraph-gateway
    tcp:
    - match:
      - port: 31400
      route:
      - weight: 100
        destination:
          host: mygraph-rabbitmq
          port:
            number: 5672
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: kubernetes
    namespace: default
  spec:
    hosts:
    - kubernetes.renlm.cn
    gateways:
    - istio-system/mygraph-gateway
    tls:
    - match:
      - port: 15443
        sniHosts:
        - kubernetes.renlm.cn
      route:
      - weight: 100
        destination:
          host: kubernetes.default.svc.cluster.local
          port:
            number: 6443