apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: istio-kube-apiserver
    namespace: kube-system
    labels:
      component: kube-apiserver
      tier: control-plane
  spec:
    type: ClusterIP
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    selector:
      component: kube-apiserver
      tier: control-plane
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: istio-kube-apiserver
  spec:
    hosts:
    - kubernetes.renlm.cn
    gateways:
    - istio-system/mygraph-gateway
    tls:
    - match:
      - port: 443
        sniHosts:
        - kubernetes.renlm.cn
      route:
      - weight: 100
        destination:
          host: istio-kube-apiserver.kube-system.svc.cluster.local
          port:
            number: 443
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: mygraph
  spec:
    hosts:
    - mygraph.renlm.cn
    gateways:
    - istio-system/mygraph-gateway
    http:
    - match:
      - port: 80
      - port: 443
      route:
      - weight: 100
        destination:
          host: mygraph
          port:
            number: 8080
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: mygraph-jenkins
  spec:
    hosts:
    - jenkins.renlm.cn
    gateways:
    - istio-system/mygraph-gateway
    http:
    - match:
      - port: 80
      - port: 443
      route:
      - weight: 100
        destination:
          host: mygraph-jenkins
          port:
            number: 8080
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: mygraph-rabbitmq
  spec:
    hosts:
    - rabbitmq.renlm.cn
    gateways:
    - istio-system/mygraph-gateway
    http:
    - match:
      - port: 80
      - port: 443
      route:
      - weight: 100
        destination:
          host: mygraph-rabbitmq
          port:
            number: 15672
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: mygraph-mysql
  spec:
    hosts:
    - "*"
    gateways:
    - istio-system/mygraph-gateway
    tcp:
    - match:
      - port: 31400
      route:
      - weight: 100
        destination:
          host: mygraph-mysql
          port:
            number: 3306