# https://fleet.rancher.io/ref-fleet-yaml
# https://github.com/rancher/fleet-examples
namespace: renlm
helm:
  chart: https://renlm.gitee.io/helm/repo/mygraph-0.1.0.tgz
targetCustomizations:
- name: dev
  clusterSelector:
    matchLabels:
      env: dev
  helm:
    valuesFiles:
    - values/dev.yaml
- name: test
  clusterSelector:
    matchLabels:
      env: test
  kustomize:
    dir: overlays/test
  helm:
    valuesFiles:
    - values/test.yaml
- name: prod
  clusterSelector:
    matchLabels:
      env: prod
  kustomize:
    dir: overlays/prod
  helm:
    valuesFiles:
    - values/prod.yaml