# https://fleet.rancher.io/ref-fleet-yaml
# https://github.com/rancher/fleet-examples
helm:
  chart: mygraph
  repo: https://renlm.github.io/helm/repo
  releaseName: mygraph
  version: 1.0.1
defaultNamespace: renlm
targetCustomizations:
- name: mygraph
  clusterSelector:
    matchLabels:
      env: prod
  kustomize:
    dir: overlays
  helm:
    valuesFiles:
    - overlays/values.yaml
    values:
      initDb: true