# https://fleet.rancher.io/ref-fleet-yaml
# https://github.com/rancher/fleet-examples
namespace: renlm
helm:
  chart: mygraph
  repo: https://renlm.gitee.io/helm/repo
  version: 0.1.0
targetCustomizations:
- name: mygraph
  clusterName: local
  kustomize:
    dir: overlays
  helm:
    valuesFiles:
    - overlays/values.yaml