# https://fleet.rancher.io/ref-fleet-yaml
# https://github.com/rancher/fleet-examples
helm:
  chart: ./chart
  releaseName: mygraph
defaultNamespace: renlm
targetCustomizations:
- name: mygraph
  clusterSelector:
    matchLabels:
      env: prod
  kustomize:
    dir: overlays
  helm:
    valuesFiles:
    - overlays/values.yaml
    values:
      appVersion: v1
      env: prod
      initDb: true
      host: mygraph.renlm.cn