apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: jenkins
spec:
  hosts:
  - {{ .Values.host }}
  gateways:
  - istio-system/gateway
  http:
  - match:
    - port: 80
    - port: 443
    route:
    - destination:
        host: jenkins
        port:
          number: 8080