apiVersion: v1
kind: ConfigMap
metadata:
  name: mygraph-configmap
data:
  dev.yaml: |-
    server:
      port: 80
      servlet:
        session:
          cookie:
            name: MYGRAPH
      tomcat:
        remoteip:
          remote-ip-header: X-Forwarded-For
          protocol-header: X-Forwarded-Proto
    my:
      config:
        ctx: http://localhost/mygraph
        wsHost: ws://localhost
        wsAllowedOrigins: http://localhost
        chrome:
          driverPath: D:/chrome/chromedriver.exe
          sleepTime: 800
    encrypt:
      keyStore:
        location: classpath:keyStore.jks
        password: ${KEY_STORE_PASSWORD:storepass}
        alias: ${KEY_STORE_ALIAS:alias}
        secret: ${KEY_STORE_SECRET:keypass}
    aj:
      captcha:
        cacheType: redis
        jigsaw: classpath:images/jigsaw
        picClick: classpath:images/pic-click
        type: default
        waterMark: localhost
        slipOffset: 5
        aesStatus: true
        interferenceOptions: 0
    mica:
      xss:
        enabled: true
        trimText: true
        mode: clear
        prettyPrint: false
        enableEscape: false
        pathPatterns: /**
        pathExcludePatterns:
        - /static
        - /webjars
        - /markdown/**
    logging:
      level:
        root: info
        cn.renlm.mygraph: debug
      file:
        name: /opt/log/mygraph.log
      logback:
        rollingpolicy:
          maxFileSize: 512MB
          maxHistory: 30
    mybatis-plus:
      configuration:
        localCacheScope: STATEMENT
      global-config:
        db-config:
          update-strategy: IGNORED
    management:
      server:
        port: 9000
      endpoints:
        web:
          exposure:
            include: prometheus
      metrics:
        tags:
          application: mygraph
    spring:
      application:
        name: mygraph
      main:
        allow-circular-references: true
      servlet:
        multipart:
          max-file-size: 30MB
          max-request-size: 30MB
      thymeleaf:
        cache: false
      jackson:
        serialization:
          WRITE_DATES_AS_TIMESTAMPS: true
      data:
        redis:
          database: 1
          host: renlm.cn
          port: 30379
          password: PWD@20xx$
          timeout: 10s
          lettuce:
            pool:
              maxActive: 256
              maxWait: 2000ms
              maxIdle: 10
              minIdle: 5
      rabbitmq:
        virtual-host: /mygraph
        host: renlm.cn
        port: 30672
        username: mygraph
        password: PWD@20xx$
      datasource:
        dynamic:
          primary: master
          strict: true
          datasource:
            master:
              url: jdbc:mysql://renlm.cn:30306/mygraph?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true
              username: mygraph
              password: PWD@20xx$
              driver-class-name: com.mysql.cj.jdbc.Driver
        sql:
          init:
            mode: always
            schemaLocations:
            - classpath:db/schema/schema.sql
            - classpath:db/schema/oauth2.sql
            - classpath:org/springframework/security/oauth2/server/authorization/oauth2-authorization-schema.sql
            - classpath:org/springframework/security/oauth2/server/authorization/oauth2-authorization-consent-schema.sql
            - classpath:org/springframework/security/oauth2/server/authorization/client/oauth2-registered-client-schema.sql
            dataLocations:
            - classpath:db/data/sys.sql
            - classpath:db/data/dict.sql
            - classpath:db/data/ds-er.sql
            - classpath:db/data/doc.sql
            - classpath:db/data/oauth2.sql
            continueOnError: false
            separator: ;
      quartz:
        job-store-type: jdbc
        jdbc:
          initialize-schema: always
        properties:
          org:
            quartz:
              scheduler:
                instanceId: AUTO
              jobStore:
                class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
                driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
                tablePrefix: QRTZ_
                isClustered: true
                misfireThreshold: 60000
                clusterCheckinInterval: 5000
                useProperties: false
              threadPool:
                class: org.quartz.simpl.SimpleThreadPool
                threadCount: 10
                threadPriority: 5
                threadsInheritContextClassLoaderOfInitializingThread: true
