apiVersion: v1
kind: ConfigMap
metadata:
  name: mygraph-configmap
data:
  dev.yaml: |-
    {{ .Files.Get "properties/dev.yaml" }}
  test.yaml: |-
    {{ .Files.Get "properties/test.yaml" }}
  prod.yaml: |-
    {{ .Files.Get "properties/prod.yaml" }}