fullnameOverride: rabbitmq
appVersion: management
gateway: istio-ingress/gateway
host: rabbitmq.renlm.cn
nodeSelector: {}
image:
  repository: rabbitmq
  pullPolicy: IfNotPresent
  tag: management
serviceAccount:
  create: false
ingress:
  enabled: false
service:
  type: NodePort
  port: 15672
  amqpPort: 5672
  amqpNodePort: 30672
nfs:
  enabled: false
  storage: 5Gi
  path: /nfs_share/rabbitmq
  server: 192.168.16.3