fullnameOverride: mysql
appVersion: latest
mini: true
nodeSelector: {}
image:
  repository: mysql
  pullPolicy: IfNotPresent
  tag: latest
serviceAccount:
  create: false
ingress:
  enabled: false
service:
  type: NodePort
  port: 3306
  nodePort: 30306
nfs:
  enabled: false
  storage: 25Gi
  path: /nfs_share/mysql
  server: 192.168.16.3