fullnameOverride: mysql
mini: true
database: dev
user: dev
nodeSelector: {}
image:
  repository: mysql
  pullPolicy: IfNotPresent
  tag: 8.0.31
serviceAccount:
  create: false
ingress:
  enabled: false
service:
  type: NodePort
  port: 3306
  nodePort: 30306
nfs:
  enabled: false
  storage: 25Gi
  path: /nfs_share/mysql
  server: 192.168.16.3