apiVersion: v1
kind: Service
metadata:
  name: {{ include "mygraph.fullname" . }}
  labels:
    {{- include "mygraph.labels" . | nindent 4 }}
    {{- range .Values.prometheus.selector }}
      {{ .name | nindent 4 }}: {{ .value }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.prometheus.port }}
      targetPort: {{ .Values.prometheus.port }}
      protocol: TCP
      name: {{ .Values.prometheus.portName }}
  selector:
    {{- include "mygraph.selectorLabels" . | nindent 4 }}
