server:
  port: 8090
  tomcat:
    remoteip:
      remote-ip-header: "x-forwarded-for"
      protocol-header: "x-forwarded-proto"
    
logging:
  level:
    root: info
    cn.renlm.graph: info
  file:
    name: /opt/log/my-graph.log
    max-size: 512MB
    max-history: 30
    
mybatis-plus:
  configuration:
    localCacheScope: STATEMENT
    cacheEnabled: true
  global-config:
    db-config:
      update-strategy: IGNORED

spring:
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  thymeleaf:
    cache: false
  jackson: 
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  datasource:
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          url: jdbc:mysql://renlm.cn:3306/graph?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true
          username: graph
          password: Kusbnjlsdi^df4K_fywm86erp7IMYt^tn504