management:
  server:
    port: 9000
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        basePath: /actuator
        include: health,shutdown,metrics,prometheus