server:
  tomcat:
    remoteip:
      remote-ip-header: "X-Forwarded-For"
      protocol-header: "X-Forwarded-Proto"
    
my:
  config:
    ctx: https://mygraph.renlm.cn
    wsHost: ws://mygraph.renlm.cn
    wssHost: wss://mygraph.renlm.cn:443
    wsAllowedOrigins: http://mygraph.renlm.cn,https://mygraph.renlm.cn
    proxyLogConcurrency: 30-50
    
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:123654}
    
mica:
  xss:
    enabled: true
    trim-text: true
    mode: clear
    pretty-print: false
    enable-escape: true
    path-patterns: /**
    path-exclude-patterns: 
      - /static
      - /webjars
      - /markdown/**
    
logging:
  level:
    root: info
    cn.renlm.graph: info
  file:
    name: /opt/log/mygraph.log
    max-size: 512MB
    max-history: 30
    
mybatis-plus:
  configuration:
    localCacheScope: STATEMENT
  global-config:
    db-config:
      update-strategy: IGNORED

spring:
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  thymeleaf:
    cache: false
  jackson: 
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  redis:
    database: 5
    host: ENC(IBsqos+iXOMHj3QP8WuIKD03TE/0JiNyWdlp60WsQX3bwwjfsk8Ab0JZdCjmFXoD)
    port: ENC(Y6RNLs6eFkRUHa8xNUlrzGdSnGhxedOiSEDcrzacuZVxRoBHH8utSFrG5+vuTCrU)
    password: ENC(kvMVW92bXK7Ym2drMqz81542HlHnpGWV+1FMPnjXcctU/Q0bAtQuN2rLe16BAZE3ZCOn+CWhThK/Qsep+/q8/xG4YV03mdP+grGgQXUXeTg=)
    timeout: 6s
  rabbitmq:
    virtual-host: ENC(O+epS5yMEqegl+pivZk2UzPRPGyaqfL1huSETOdu0lAlgEfU6mSEJknKKtc2ozm9)
    host: ENC(upHWfmrHToOZ8qDU8xMLAflxsPZ61D0cWQaTitGGZNQqdPW+edeVGZngnpEk/EiN)
    port: ENC(Br0y9BJ1TfC/CYtAkM9Ij0Q6z5pzy6WJRY6o/d4DZducoP5weMIRp0jdYY+RIVdm)
    username: ENC(x7mQELG8zbtqpDhykzDoy2ZqMSs1HHBK6FRWrfFptc8AX28/ABnWNOY9QNFMQ1pb)
    password: ENC(mKnxCAS26wM7tYsW2pG8hjYS6JY2/iAoS5v/UkM7IniEvu8JHJWFvfrZdclGnw5oHhQwotXp83M5IJho02MC5ZmGn9FtSBr3cEtSe5xn2VM=)
    listener:
      direct:
        missing-queues-fatal: false
  datasource:
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          url: ENC(l0VmB743xPY1w+/bEI2iNuIuSEPyXgOeMU2NW72cjBAvD9TRjBBbkRNxc6zc2RMpKynET53x3A/Q/DyLcnYvFND/UHCFfV/z9GhSJg8kKnYBKr8Be53cBIq5X3iJnsn3iDljDyulGBzdfWc4PQZ4Wi/gmH6Dxay99j7GPksErOoy+AnWeWE3Nf4GUMmlonelVasoSXsdxurXcHKOZv/Qlw==)
          username: ENC(TH8gokJSLbQ6b+3miT2omUUP2ymJzM14ItGSYD9dZ2W4/pzFusZeCvwkuY1nFL4l)
          password: ENC(DP2Al147pJyiFArv67h0Pm08fFWjX9Ktjyri2jXjBm4ZWYsnSwXBwOsdk7ndmNmKJu8QjXCg7oDhIqQy9HnAcw==)
          driver-class-name: com.mysql.cj.jdbc.Driver
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            misfireThreshold: 60000
            clusterCheckinInterval: 5000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true