server:
  tomcat:
    remoteip:
      remote-ip-header: "X-Forwarded-For"
      protocol-header: "X-Forwarded-Proto"
    
my:
  config:
    ctx: https://mygraph.renlm.cn
    wsHost: ws://mygraph.renlm.cn
    wssHost: wss://mygraph.renlm.cn:443
    wsAllowedOrigins: http://mygraph.renlm.cn,https://mygraph.renlm.cn
    proxyLogConcurrency: 30-50
    
mica:
  xss:
    enabled: true
    trim-text: true
    mode: clear
    pretty-print: false
    enable-escape: false
    path-patterns: /**
    path-exclude-patterns: 
      - /static
      - /webjars
      - /markdown/**
    
logging:
  level:
    root: info
    cn.renlm.graph: info
  file:
    name: /opt/log/mygraph.log
    max-size: 512MB
    max-history: 30
    
mybatis-plus:
  configuration:
    localCacheScope: STATEMENT
  global-config:
    db-config:
      update-strategy: IGNORED

spring:
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  thymeleaf:
    cache: false
  jackson: 
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  redis:
    host: redis
    port: 6379
    timeout: 6000
    password: Kusbnjlsdi^df4K_fywm86erp7IMYt^tn504
    database: 3
    client-name: mygraph
  rabbitmq:
    virtual-host: /mygraph
    host: rabbitmq
    port: 5672
    username: mygraph
    password: Kusbnjlsdi^df4K_fywm86erp7IMYt^tn504
    listener:
      direct:
        missing-queues-fatal: false
  datasource:
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          url: jdbc:mysql://mysql:3306/mygraph?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true
          username: mygraph
          password: Kusbnjlsdi^df4K_fywm86erp7IMYt^tn504
          driver-class-name: com.mysql.cj.jdbc.Driver
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            misfireThreshold: 60000
            clusterCheckinInterval: 5000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true