{{- if .Values.nfs.enabled -}}
{{- $fullName := include "mysql.fullname" . -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $fullName }}-pv
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  volumeMode: Filesystem
  storageClassName: {{ $fullName }}-sc
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: {{ .Values.nfs.storage }}
  accessModes:
    - ReadWriteOnce
  nfs:
    path: {{ .Values.nfs.path }}
    server: {{ .Values.nfs.server }}
{{- end -}}